### ISSUE TITLE
problem about training

### ISSUE THREAD

**Issue by linjikun1** [ziansu/prorec#1]
When I typed in the following command, 

`torchrun --nproc_per_node=4 run_casp.py scripts/configs/train_casp_moco.yaml`

I found that the training was progressing too slowly, taking over 20 hours.

![a8bf63d80b92925f131bbfd08310fe7](https://github.com/user-attachments/assets/1824e4a5-0d00-4386-b36a-d15b135d778e)

Here's the GPU usage after I connected the wandb.
![4d8afe719631930ff94613b7760603c](https://github.com/user-attachments/assets/1a35d669-875b-4d80-a0d9-3a71ac09a089)

I want to know why it's so slow. Is it because it's supposed to be that way or is it some other problem?

By the way, could you please consider providing **the corresponding docker image**? I would be very grateful.

**Comment by ziansu** [comment]
Thank you for your interest!

Your GPU utilization is indeed a bit low. That might because in the provided config the `per_device_train_batch_size` is set to 8. If you double them to 16 and the utilization will be around 100%. ![GPU Utilization](https://github.com/user-attachments/assets/6f73cb36-d665-4730-9d3b-697ac5cbf353)

On the other hand, for our downstream experiments, we used the checkpoint after 10k steps, which means you can further save some time by early stopping (terminate the process when it reaches certain steps and the checkpoint is evaluated and saved). Also, it seems you have more than 4 GPUs so maybe you can try to allocate more GPUs for parallel training.

We will consider providing a docker image later. However, we are busy at the moment so you might need to wait for a while. Since you are already able to train the prober, I think the environment is not a big problem.

**Comment by linjikun1** [comment]
**Thank you for your reply! But I still have some questions.**

**1.** I wonder if these four commands are training the model **step by step**?

`torchrun --nproc_per_node=4 run_casp.py scripts/configs/train_casp_moco.yaml`
`torchrun --nproc_per_node=4 run_prober.py scripts/configs/train_prober.yaml`
`accelerate launch --num_processes=4 big_model_quantized_probing.py scripts/configs/probe_quantized_codellama-34b-4bit-unfreeze.yaml`
`python score_and_filter_signature.py scripts/configs/filter_sig.yaml`

Does it mean I need to execute the above four commands **first** to get a pretrained model if I want to do some inference?

**2.** I noticed you mentioned inference scripts.

> We provide representive scripts for training and inference.

How should I start for inference? 

**3.** If I want to do some inference (e.g., for Binary Summarization), what should be my inputs and the outputs of the model？

**Comment by ziansu** [comment]
Sorry for the late response. We are quite busy at the moment.

1. About the commands, the `run_casp.py` is for training a cross-modal retriever; `run_prober.py` is for training the prober; `big_model_quantized_probing.py` is for inferencing the signature; `score_and_filter_signature.py` is for filtering the signature; and `big_model_quantized_probing_continue.py` is for inference the rest of the function body given the filtered signatures. If you want to reproduce the whole pipeline, you will need to run these scripts step by step and possibly modify some configurations.
2. Our pre-trained models are hosted on Hugging Face. Please check https://huggingface.co/PurCL for checkpoints. For the default inference configuration (`probe_quantized_codellama-34b-4bit-unfreeze.yaml`) we are actually using the pre-trained checkpoint hosted on HF). If you have your own paired binary-source function corpus, we recommend using the corpus for prober training in order to adapt to that distribution and inference with the new prober.
3. For inference data format, you can check line 202-204 in `big_model_quantized_probing.py`, which essentially is the Hugging Face dataset containing a `codeart` field. The `codeart` field is a dictionary containing two subfields: `code` and `dep`. For how to preprocess and get such fields, please check our codeart repo https://github.com/ziansu/codeart.

**Comment by linjikun1** [comment]
Hi,
I want to ask the difference between retriever and prober. My initial understanding for whole work is that:

- We firstly align binary encoder and souce code encoder to form a dual_encoder which is also called retriever. It takes a binary(actually a decomC function) as a input, generates the TOP_K relevant **_hsrc_**(actually a source code embedding, or called **_function signature_**) according to **_sim(xasm, xsrc) = cos (hasm, hsrc)_**. That is what the retriever need to do.
- Then we align binary encoder and SCFM(actually a decoder) to decode the TOP_K hsrc getting from retriever to generate the TOP_K revelant source code contexts.
- Retriever is a part of prober. When we give prober a decomC as a input, it finally synthesize revelant contexts.

But the below note from the paper really makes me confused.

> We leverage nucleus sampling to first let the prober generate a relatively large set of source function signatures with high randomness (top-p = 0.75). We use idea similar to retrieval by training a binary-signature dual-encoder to rank generated signatures and filter out the noisy ones. Ultimately, we use the prober to further complete the remaining signatures with smaller randomness (top-p = 0.5).

It feels as if retriever and prober are two modules that work independently.

It has confused me for a long time. If there is anything wrong with my understanding, please help me.

**Hope for your guidance!**

**Comment by ziansu** [comment]
The retriever and prober indeed work independently **during inference**. However, there is some overlap in the training process.

### How the dual-encoder dense retriever works

As you already understand how similarity score is computed, our retrieval-augmented baseline only use the retrieved top-k source functions, i.e., the source functions with the highest similarity scores, as additional context (which is quite straightforward). Note that there is no need to **decode** the h_src since we already have the source functions within the datastore (which consists of all the source functions in the training set). Otherwise, we can not obtain the h_src which is the encoded source functions, in the first place.

### How the prober works

There is no retrieval process for the prober, it is actually an encoder-decoder. The encoder part of the prober encodes the x_asm once and obtain the intermediate hidden states (the Zs as in Figure 2). Then, the intermediate hidden states will be fed into the SCFM for decoding. The decoding will have some randomness so that some sampling will provide diverse source code snippets.

### Overlaps in training

The overlap in the training is due to both retriever and prober contains the codeart encoder (same architecture but prober's further alignment training make the parameters different). 

### Additional notes

Note that we only use disassembled code for retrieval/probing, you can probability also use decompiled code and more information (e.g., [LMPA](https://xz-x.github.io/lmpa-github.pdf) uses some information from dependent context for variable name recovery) from the binary code in the future.

**Comment by linjikun1** [comment]
Hi, 

Thank you for your patient guidance and there are some problems still. 

- What is signature in this context? The Zs as in Figure 2? If so, why is it called source code signature rather than asm signature? And how is the signature here obtained? From encode part of prober?
  > We leverage nucleus sampling to first let the prober generate a relatively large set of source function signatures with high randomness (top-p = 0.75).

- What does`a binary-signature dual-encoder` mean? Does it mean using binary-signature corpus to retrain a binary-signature dual-encoder?
  > We use idea similar to retrieval by training a binary-signature dual-encoder to rank generated signatures and filter out the noisy ones.

- Does it mean the decoding stuff?
  > Ultimately, we use the prober to further complete the remaining signatures with smaller randomness (top-p = 0.5).

My purpose is use [other dataset](https://drive.google.com/drive/folders/1vN3gspP4ZZPOHW-bA42iWiZ3hiOyKp3X) as input for **prorec** to get function summary. Now I'm stuck on not knowing how to use [your pretrained prober](https://hf-mirror.com/PurCL/src_prober_codellama-34b-last1unfreeze) to receive disassembled as input and get discomC with relevant context for output. And your code structure is so ultra-refined and precise that I often get lost. So do you have any suggestions for direct interence to get function summary by using the **prorec** structure?

**Sincere appreciation and expectation for your reply!**

**Comment by ziansu** [comment]
1. "Signature" means something like `int main(int argc, char *argv[])`. We simply want to sample better source code generated by the prober, but generating the full function can be time and GPU-memory consuming for a large amount of candidates, so in this work we first generate short signature of the function, do some filtering, and then generate the following tokens. In practice, if you have enough computation resource or acceleration (there should be some inference acceleration frameworks for multimodal models recently, but how to support prober within these frameworks will be a problem), it is possible to directly sample full source functions and filter them with the retriever.
2. Your understanding is correct. The binary-signature dual-encoder is indeed a retrained one. The training script `run_casp_signature.py` is similar to `run_casp.py`, with only some difference in `collate_fn` so we can use the original binary-source dataset for binary-signature training.
3. Right. This means we continue decoding with the encoder outputs and previously generated function signatures.

---

For inferencing with the prober, the input should comply with the format of the `codeart` field in our dataset, which is a json-dumped dictionary of `code` and `dep`. For the preprocessing of codeart format, you can check https://github.com/ziansu/codeart/tree/artifacts/codeart/preprocess. And maybe @XZ-X can help answer some questions related to preprocessing.

**Comment by XZ-X** [comment]
I am happy to help with preprocessing.

The preprocess code for CodeArt is at [here](https://github.com/ziansu/codeart/tree/artifacts/codeart/preprocess), as Zian suggested before. Let me know if you have further questions.

Alternatively, we can also run the preprocessing part for you if that's a better solution. In that case, would you share with us the **unstripped** binaries? And we will share the preprocessed file. You can start your experiments from the training/inference part then.

**Comment by ljk419511** [comment]
**I'm so sorry for the late reply.**

@XZ-X  With the permission of the original author, I've put the dataset [here](https://drive.google.com/drive/folders/1pWubTaCybpf7Dvw-icz88QOzw_NupfNP).

When I run [analyze.py](https://github.com/ziansu/codeart/blob/artifacts/codeart/preprocess/analyze.py), I get the following error.

> Traceback (most recent call last):
  File "/home/ljk/study/codeart/codeart/preprocess/analyze.py", line 65, in <module>
    main()
  File "/home/ljk/study/codeart/codeart/preprocess/analyze.py", line 38, in main
    'project_name': function['project_name'],
TypeError: string indices must be integers

It looks like [data_in](https://github.com/ziansu/codeart/blob/d7dc61aa80d7026a4b2b0f691ff9c15ad924d40a/codeart/preprocess/analyze.py#L27) needs to be a dict type whose elements are dict. I try to print the information about data_in and [function](https://github.com/ziansu/codeart/blob/d7dc61aa80d7026a4b2b0f691ff9c15ad924d40a/codeart/preprocess/analyze.py#L30) like `print(type(data_in))`, `print(data_in)` and `print(type(function))`. Then I got the following results.

> <class 'dict'>
{
'start': [4299165696, ['sub     rsp, 28h', 'lea     rcx, sub_1004017E0', 'call    sub_100401210', 'xor     r8d, r8d', 'xor     edx, edx', 'xor     ecx, ecx', 'call    nullsub_1', 'xor     r8d, r8d', 'xor     edx, edx', 'xor     ecx, ecx', 'call    nullsub_2', 'xor     r8d, r8d', 'xor     edx, edx', 'xor     ecx, ecx', 'call    nullsub_3', 'xor     r8d, r8d', 'xor     edx, edx', 'xor     ecx, ecx', 'add     rsp, 28h', 'jmp     nullsub_4'], b'H\x83\xec(H\x8d\r\xd5\x07\x00\x00\xe8\x00\x02\x00\x00E1\xc01\xd21\xc9\xe8\x14\x02\x00\x00E1\xc01\xd21\xc9\xe8\x18\x02\x00\x00E1\xc01\xd21\xc9\xe8\x1c\x02\x00\x00E1\xc01\xd21\xc9H\x83\xc4(\xe9\x1c\x02\x00\x00', <networkx.classes.digraph.DiGraph object at 0x7a6deff97d60>, None], 
'sub_100401050': [4299165776, ['lea     r8, unk_100402000; lpdso_handle', 'xor     edx, edx; obj', 'lea     rcx, func; lpfunc', 'jmp     __cxa_atexit'], b'L\x8d\x05\xa9\x0f\x00\x001\xd2H\x8d\r\x10\x00\x00\x00\xe9\xab\x00\x00\x00', <networkx.classes.digraph.DiGraph object at 0x7a6defedcb50>, None],
...
}
<class 'str'>

The above data_in result from [here](https://github.com/ziansu/codeart/blob/d7dc61aa80d7026a4b2b0f691ff9c15ad924d40a/codeart/preprocess/disassemble.py#L115) seem to contradict the [code](https://github.com/ziansu/codeart/blob/d7dc61aa80d7026a4b2b0f691ff9c15ad924d40a/codeart/preprocess/analyze.py#L31). That makes me confused.

**Hope for your reply!**

**Comment by linjikun1** [comment]
**So sorry for the late reply.**

@XZ-X  With the permission of the original author, I've put the dataset [here](https://drive.google.com/drive/folders/1pWubTaCybpf7Dvw-icz88QOzw_NupfNP).

I've finished formatting the data and got the jsonl file in the following format.

```
{
    "metadata": {
        "project_name": , 
        "function_name": , 
        "function_addr": , 
        "binary_name": 
    }, 
    "code": [

    ], 
    "data_dep": [

    ]
}
{
    ...
}
```

- Do I need to do anything else with the jsonl data?
- What should I do next?

**Comment by XZ-X** [comment]
It seems that I cannot access the google drive link. Please double check the access control.

Did you mean you've successfully run the preprocessing pipeline and got the jsonl file?

**Comment by linjikun1** [comment]
I'm sorry. [It](https://drive.google.com/drive/folders/1pWubTaCybpf7Dvw-icz88QOzw_NupfNP?usp=sharing) should be okay now.

Yes, I think that I've finished the preprocessing and got the jsonl file with the format of the codeart field according to [here](https://github.com/ziansu/codeart/tree/main/codeart/preprocess). But the follow error seems to indicate that further processing of the jsonl data is still required.

> Traceback (most recent call last):
>   File "/home/featurize/linjk/prorec/src/big_model_quantized_probing.py", line 461, in <module>
>     main()
>   File "/home/featurize/linjk/prorec/src/big_model_quantized_probing.py", line 444, in main
>     results = batch_inference(
>   File "/home/featurize/linjk/prorec/src/big_model_quantized_probing.py", line 203, in batch_inference
>     [eval(example['codeart']) for example in examples]
>   File "/home/featurize/linjk/prorec/src/big_model_quantized_probing.py", line 203, in <listcomp>
>     [eval(example['codeart']) for example in examples]
> KeyError: 'codeart'

Besides, I'd also like to ask what I should do as a follow-up for inferencing with the prober.

Looking forward to your reply.

**Comment by ziansu** [comment]
You should convert the jsonl into a Hugging Face dataset.

```python
from datasets import Dataset, DatasetDict

dataset = Dataset.from_dict{'codeart': [repr({'code': ..., 'dep': ...}) for ... in your_jsonl_list]})
dataset = DatasetDict({'test': dataset})


# you can either pub it to hub
dataset.push_to_hub('path_to_your_hub')
# or you can save to disk
dataset.save_to_disk('path_to_dir')
```

Then, you can run `accelerate launch --num_processes=4 big_model_quantized_probing.py scripts/configs/probe_quantized_codellama-34b-4bit-unfreeze.yaml` with some modifications within the config .yaml file and potentially some lines in the .py file.

1. If you pushed the dataset to hub, then you can modify the `dataset_name` field in the .yaml file to your dataset name on the hub.
2. If you saved the dataset to disk, then a relative easy way to load the dataset is to change line 300-343 in `big_model_quantized_probing.py` to `dataset = load_from_disk('path_to_dir')`.

**Comment by linjikun1** [comment]
Whether I use 1 RTX4090 or 4 RTX4090, It all throws the **CUDA Out Of Memory** error, only if batch_size=1 it will not. And the training progress is unbearably slow. Can't even tell the difference between 1 GPU and 4 GPUs from training speeds.

- In order to reduce the GPU memory requirements, I set `num_return_sequences` [here](https://github.com/ziansu/prorec/blob/e7f8fb36d8c819be002f2f263c3d6796c14a4ccd/src/scripts/configs/probe_quantized_codellama-34b-4bit-unfreeze.yaml#L11) to 10. I'm not sure if this modification is appropriate at the moment.
- For inference, I think the order of execution of the script is, to run `big_model_quantized_probing.py` to generate the function signature, run `score_and_filter_signature.py` to filter the signature, run `big_model_quantized_probing_continue.py` to decode the remainder of the generated function. And I'm not quite sure if I'm on the right track.
- It's not clear to me at the moment how the pseudo-code is fetched in your method, because in my understanding the probed contexts are needed as additional contexts for the pseudo-code.
- Considering that the purpose of `big_model_quantized_probing_continue.py` is to generate the subsequent content, I've set the `num_return_sequences `of that script to 1. And I'm not sure it's appropriate to do so.

**looking forward to your guidance!**

**Comment by ziansu** [comment]
- Training speed can depend on bandwidth to communicate between GPUs. 4090 has half of A100's bandwith and no nvlink, so there can be some bottleneck there. You might want to integrate some training frameworks such as DeepSpeed to accelerate training, but we have not tested such possibilities.

- For `num_return_sequences`, if you want to have the same amount of the total sampled results, you can reduce it and run inference multiple times with different seeds.

- The inference order is correct.

- I guess the *pseudo-code* here means the decompiled C-like code (as named in CP-BCS). We are using [IDA](https://hex-rays.com/ida-pro) to decompile the binaries. Maybe @XZ-X can help you with it.

- The `num_return_sequence` is indeed 1 for each signature in `example['candidate_signatures'][:n_candidates]` (check line 212-213 in `big_model_quantized_probing_continue.py`).

**Comment by linjikun1** [comment]
Thanks for the thorough help. And I eagerly look forward to your guidance. @XZ-X

**Comment by XZ-X** [comment]
Sorry for the late response. Attached is the IDA script I used to decompile binaries:

```python
import idaapi
import idc
import idautils
import os
import sys

# load decompiler plugin for ida python 3
idaapi.load_plugin("hexrays")
idaapi.load_plugin("hexx64")

# given a function address, return the decompiled code
def get_decompiled_code(func_addr):
    # get the function name
    func_name = idc.get_func_name(func_addr)
    # get the function start address
    func_start = func_addr
    # get decomiled code
    decompiled_code = str(idaapi.decompile(func_start))    
    return (func_start, func_name, decompiled_code)

# auto wait
idaapi.auto_wait()

ret = []
# get the address of .text section
# text_addr_begin = idaapi.get_segm_by_name(".text").startEA
# text_addr_end = idaapi.get_segm_by_name(".text").endEA

# print ("Text range: %x - %x" % (text_addr_begin, text_addr_end))
# get all functions in the binary
for func in idautils.Functions():
    # # uncomment the following lines if you only want to decompile the .text section
    # if func < text_addr_begin or func > text_addr_end:
    #     continue

    # get the decompiled code
    try:
      decompiled = get_decompiled_code(func)
      ret.append(decompiled)
    except:
      continue

# get input file name
input_file = idc.get_input_file_path()
# get the output file name
output_file = input_file + ".decompiled"

# dump ret as json
import json
with open(output_file, "w") as f:
    json.dump(ret, f)


idaapi.qexit(0)
```

Since you already got the preprocessed data with the `codeart` format, I guess you figured how to use IDA python. Please feel free to ping me if you run into problems.

-------

Btw, the above script is only tested on `x86-64` binaries. I guess it also works for `x86` binaries. But I'm not sure whether it works for the `arm` binaries.  I mention this because I found the data you shared before contain `arm` and `x86` binaries. 

Also note that the pre-trained `codeart` model only works on `x86-64` binaries because we reuse the `jTrans` dataset that only contains `x86-64` binaries at the time of our publication. 
If you want to analyze binaries for other architecture, maybe it is necessary to run the pre-training on the corresponding architectures.

**Comment by XZ-X** [comment]
Just realized another point: We trained/tested ProRec on `O0` binaries only, while it seems that your dataset contains only `O1--O3` binaries. The frontend (i.e.,`codeart`) is trained on binaries from `O0` to `O3`, so I guess you can still try the dataset with ProRec. 

That said, you may want to run the training pipeline on some `O1` to `O3` data entries if you found the results not helpful enough. Either way, feel free to ping us if you need further help.
