### ISSUE TITLE
ValueError: Unknown split "train". Should be one of ['test'].

### ISSUE THREAD

**Issue by linjikun1** [ziansu/prorec#2]
When I try to run the following command,

> `accelerate launch --num_processes=4 big_model_quantized_probing.py scripts/configs/probe_quantized_codellama-34b-4bit-unfreeze.yaml`

I got the following error,

Traceback (most recent call last):
  File "/home/linjk/prorec/src/big_model_quantized_probing.py", line 461, in <module>
    main()
  File "/home/linjk/prorec/src/big_model_quantized_probing.py", line 311, in main
    dataset["validation"] = load_dataset(
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/load.py", line 2149, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/builder.py", line 1190, in as_dataset
    datasets = map_nested(
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 455, in map_nested
    return function(data_struct)
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/builder.py", line 1220, in _build_single_dataset
    ds = self._as_dataset(
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/builder.py", line 1294, in _as_dataset
    dataset_kwargs = ArrowReader(cache_dir, self.info).read(
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/arrow_reader.py", line 240, in read
    files = self.get_file_instructions(name, instructions, split_infos)
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/arrow_reader.py", line 213, in get_file_instructions
    file_instructions = make_file_instructions(
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/arrow_reader.py", line 130, in make_file_instructions
    absolute_instructions = instruction.to_absolute(name2len)
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/arrow_reader.py", line 653, in to_absolute
    return [_rel_to_abs_instr(rel_instr, name2len) for rel_instr in self._relative_instructions]
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/arrow_reader.py", line 653, in <listcomp>
    return [_rel_to_abs_instr(rel_instr, name2len) for rel_instr in self._relative_instructions]
  File "/home/linjk/miniconda3/envs/torchenv/lib/python3.10/site-packages/datasets/arrow_reader.py", line 465, in _rel_to_abs_instr
    raise ValueError(f'Unknown split "{split}". Should be one of {list(name2len)}.')
**ValueError: Unknown split "train". Should be one of ['test'].**

When I check the required dataset **lmpa-prorec-test-1k**, I found the dataset splitting like this.

![a234f846ccb073d6ac44a1fce5f0abe](https://github.com/user-attachments/assets/107c1eea-3d68-4619-a945-8e76dee4cc06)

But I'm truly not sure if my question is relevant to it or not. If not, what should I do?

**Appreciate for any guidance. Thanks!**

**Comment by ziansu** [comment]
You can comment out line 310-326 in `big_model_quantized_probing.py`.
